import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, BookOpen, Bookmark, Highlighter, Library, LockKeyhole, Network, NotebookPen, Presentation, Route, Users, WifiOff, type LucideIcon } from 'lucide-react'
import { Brand, BuilderView, Button, HeroDevices, LessonParticipation, LibraryPreview, ProductVisual, ReaderView, SectionHeading, SpaceView } from './components'
import './fonts.css'
import './editorial.css'

const nav = [['study', 'Study'], ['together', 'Together'], ['teach', 'Teach'], ['about', 'About']]
const workflow: { name: string; copy: string; detail: string; icon: LucideIcon }[] = [
  { name: 'Read', copy: 'Begin with one verse or a whole chapter. Keep scripture at the center.', detail: 'Chapter & Scroller', icon: BookOpen },
  { name: 'Explore', copy: 'Follow the people, places, and events connected to the text.', detail: 'Scripture Explorer', icon: Network },
  { name: 'Save', copy: 'Keep the passages, notes, and highlights you want to return to.', detail: 'Your personal study', icon: Bookmark },
  { name: 'Build', copy: 'Bring scripture and saved study into a lesson. Add questions and your own guidance.', detail: 'Lesson Builder', icon: NotebookPen },
  { name: 'Share', copy: 'Share chosen thoughts in a Study Space. Shared lessons use their own link or Lesson Channel.', detail: 'Shared lessons in development', icon: Users },
  { name: 'Teach', copy: 'Use your lesson as a teacher. Shared participation and Live are being developed.', detail: 'Together, or at your own pace', icon: Presentation },
]
const features: { name: string; copy: string; icon: LucideIcon; href: string }[] = [
  { name: 'Reader', copy: 'One verse at a time or full chapters. A reading rhythm that fits you.', icon: BookOpen, href: './reader/' },
  { name: 'Explorer', copy: 'Source-backed people, places, events, and connections. Available offline.', icon: Network, href: './explorer/' },
  { name: 'Mastery', copy: 'Practice remembering passages, with focused exercises and review.', icon: Bookmark, href: './more/' },
  { name: 'Reading Plans', copy: 'Choose a direction, set your pace, and return to your next reading.', icon: Route, href: './more/' },
  { name: 'Notes & Highlights', copy: 'Capture what stands out, right beside the scripture that inspired it.', icon: Highlighter, href: './reader/' },
  { name: 'Library', copy: 'Keep passages and saved study close as your personal collection grows.', icon: Library, href: './more/' },
  { name: 'Study Spaces', copy: 'Private shared reading and thoughts for families, friends, and classes.', icon: Users, href: './groups/' },
  { name: 'Lessons', copy: 'Shape study into a lesson. Shared participation and Live are developing.', icon: NotebookPen, href: './lessons/' },
]

function App() {
  return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="container nav-shell"><Brand /><nav className="desktop-nav" aria-label="Primary navigation">{nav.map(([id, name]) => <a key={id} href={`#${id}`}>{name}</a>)}</nav><div className="nav-actions"><a className="button primary nav-download" href="./download/">Download Cultivate</a><details className="mobile-menu"><summary>Menu</summary><nav aria-label="Mobile navigation">{nav.map(([id, name]) => <a key={id} href={`#${id}`} onClick={event => event.currentTarget.closest('details')?.removeAttribute('open')}>{name}</a>)}<a href="./download/">Download</a></nav></details></div></div></header>
  <main id="main" tabIndex={-1}>
    <section className="hero container"><p className="tagline"><span />Read. Study. Teach. Together.</p><h1>Scripture study, built for <br /><em>more than reading.</em></h1><p className="hero-copy">Study deeply on your own. Grow together in Study Spaces.<br className="desktop-break" /> Build lessons everyone can participate in.</p><div className="actions"><Button href="./download/">Download Cultivate</Button><Button href="#experiences" secondary>Explore Cultivate</Button></div><p className="platform-note">iPhone &amp; iPad via TestFlight · Android beta</p><nav className="hero-doors" aria-label="The three Cultivate experiences"><a href="#study">Study</a><span aria-hidden="true">·</span><a href="#together">Together</a><span aria-hidden="true">·</span><a href="#teach">Teach</a></nav><HeroDevices /></section>
    <section className="experiences container" id="experiences"><SectionHeading eyebrow="Three core experiences" title={<>Designed with purpose.<br className="mobile-break" /> Built for depth.</>}>From personal discovery to shared study, each experience has a place in the same journey.</SectionHeading>
      <div className="experience" id="study"><div className="experience-copy"><p className="section-chip">Study</p><h2>Make scripture<br />study yours.</h2><p>Read one verse at a time or settle into a full chapter. Follow the people, places, and connections in Explorer. Keep notes, highlights, and passages worth returning to.</p><p>Build a reading rhythm with plans and Mastery. Go deeper offline, with no AI in the app.</p><a className="text-link" href="./reader/">Explore personal study <ArrowRight size={15} /></a></div><ProductVisual className="study-product" caption="Conceptual Reader and saved-study layout"><ReaderView /><LibraryPreview /></ProductVisual></div>
      <div className="experience reverse" id="together"><div className="experience-copy"><p className="section-chip">Together</p><h2>Scripture study<br />is better together.</h2><p>Create a private Study Space for your family, friends, or class. Share a reading plan, see cooperative progress, and bring selected thoughts from scripture into the conversation.</p><p>Your personal notes stay private until you choose to share them. Shared lesson participation is developing alongside this shared-reading experience.</p><a className="text-link terracotta" href="./groups/">Discover Study Spaces <ArrowRight size={15} /></a></div><ProductVisual className="space-product" caption="Conceptual Study Space · No real member activity shown"><SpaceView /></ProductVisual></div>
      <section className="teach-experience" id="teach"><div className="teach-heading"><div><p className="section-chip">Teach</p><h2>Turn your study<br />into a lesson.</h2><p>Bring scripture passages, personal notes, saved material, questions, and discoveries together in Lesson Builder. Keep your teaching guidance private.</p><p className="development-note">Shared and self-paced participation, participant devices, and Live sessions are in development. Availability will vary as the beta evolves.</p></div><Button href="./lessons/">Explore Lessons</Button></div><ProductVisual className="teach-builder" caption="Conceptual Lesson Builder · Replaceable with an actual app screenshot"><BuilderView /></ProductVisual><LessonParticipation /></section>
    </section>
    <section className="workflow" id="workflow"><div className="container"><SectionHeading eyebrow="Keep the thread of your study" title="One app. One study workflow.">Read → Explore → Save → Build → Share → Teach.<br />What you discover can become something you return to—and something you share.</SectionHeading><div className="workflow-grid">{workflow.map(({ name, copy, detail, icon: Icon }, index) => <article className="workflow-card" key={name}><div className="workflow-card-head"><span>{String(index + 1).padStart(2, '0')}</span><Icon size={20} aria-hidden="true" /></div><h3>{name}</h3><p>{copy}</p><div className="workflow-detail">{detail}</div></article>)}</div><p className="workflow-note">Reading Study Spaces and Lesson Channels serve different purposes. Lesson sharing and Live extend this workflow and are still developing.</p></div></section>
    <section className="depth container"><SectionHeading eyebrow="A thoughtful set of tools" title="There’s more beneath the surface.">Everything has a place. Explore a little further when you’re ready.</SectionHeading><div className="depth-grid">{features.map(({ name, copy, icon: Icon, href }) => <a className="depth-feature" href={href} key={name}><span className="feature-icon"><Icon size={18} aria-hidden="true" /></span><h3>{name}</h3><p>{copy}</p></a>)}</div></section>
    <section className="about container" id="about"><div><p className="eyebrow">Space for your own understanding</p><h2>Context to explore.<br /><em>Meaning to discover.</em></h2><p>Cultivate connects scripture and source-backed context. It leaves room for your questions, your study, and your own understanding.</p><a className="text-link" href="./labs/">Behind the connections: Cultivate Labs <ArrowRight size={15} /></a></div><div className="trust-points"><article><WifiOff size={21} /><div><h3>Useful offline.</h3><p>Read scripture, explore packaged data, browse topics, and build personal lessons. Connect for sync, sharing, group updates, and Live.</p></div></article><article><BookOpen size={21} /><div><h3>No AI in the app.</h3><p>Scripture and packaged discovery data, without generated scripture commentary.</p></div></article><article><LockKeyhole size={21} /><div><h3>Your notes. Your choice.</h3><p>Share the thoughts you choose. Keep personal study and private teacher notes your own.</p></div></article></div></section>
    <section className="download-cta" id="download"><div className="container"><p className="tagline"><span />Available to try in beta</p><h2>Study deeper. Study together.<br /><em>Teach with confidence.</em></h2><p>Start with scripture. See where your study takes you.</p><div className="actions"><Button href="./download/">Download Cultivate</Button><Button href="#study" secondary>Find your way into study</Button></div><p className="platform-note">iPhone &amp; iPad via TestFlight · Android beta</p><p className="beta-note">Features and availability may change during beta.</p></div></section>
  </main><footer><div className="container footer-grid"><div className="footer-brand"><Brand /><p>A thoughtful home for personal scripture study, shared discovery, and lessons worth returning to.</p></div><nav aria-label="Study links"><h3>Study</h3><a href="./reader/">Scripture Reader</a><a href="./explorer/">Explorer</a><a href="./topical-guide/">Topical Guide</a><a href="./more/">Mastery &amp; plans</a></nav><nav aria-label="Together links"><h3>Together &amp; Teach</h3><a href="./groups/">Study Spaces</a><a href="./lessons/">Lessons</a><a href="#workflow">The study workflow</a></nav><nav aria-label="About links"><h3>Cultivate</h3><a href="#about">Our approach</a><a href="./labs/">Cultivate Labs</a><a href="./download/">Download</a></nav></div><div className="container footer-bottom"><p>Cultivate is an independent application and is not affiliated with, nor officially supported or endorsed by, The Church of Jesus Christ of Latter-day Saints.</p><div><span>© {new Date().getFullYear()} Cultivate Study</span><a href="../privacy/">Privacy</a><a href="../account-deletion/">Account deletion</a></div></div></footer></>
}

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
