import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, BookOpen, Bookmark, Highlighter, Library, LockKeyhole, Network, NotebookPen, Presentation, Route, Users, WifiOff, type LucideIcon } from 'lucide-react'
import { Brand, BuilderView, Button, HeroDevices, LibraryPreview, ProductVisual, ReaderView, SectionHeading, SpaceView } from './components'
import { Showcases } from './showcases'
import './fonts.css'
import './editorial.css'

const nav = [['./study/', 'Study'], ['./together/', 'Together'], ['./teach/', 'Teach'], ['#about', 'About']]
const workflow: { name: string; copy: string; detail: string; icon: LucideIcon }[] = [
  { name: 'Read', copy: 'Start with one verse or read the whole chapter.', detail: 'Reader', icon: BookOpen },
  { name: 'Explore', copy: 'Follow the people, places, events, and connections behind the passage.', detail: 'Explorer', icon: Network },
  { name: 'Save', copy: 'Keep notes, highlights, passages, and discoveries you want to return to.', detail: 'Library', icon: Bookmark },
  { name: 'Build', copy: 'Bring scripture and saved material into a lesson, then add questions and teaching notes.', detail: 'Lessons', icon: NotebookPen },
  { name: 'Share', copy: 'Study with a group or publish recurring lessons to a Lesson Channel.', detail: 'Study Spaces & Channels', icon: Users },
  { name: 'Teach', copy: 'Let people participate on their own schedule or bring everyone together live.', detail: 'Async & Live', icon: Presentation },
]
const features: { name: string; copy: string; icon: LucideIcon; href: string }[] = [
  { name: 'Reader', copy: 'Slow down one verse at a time or read complete chapters.', icon: BookOpen, href: './reader/' },
  { name: 'Explorer', copy: 'Discover people, places, events, stories, groups, and connections.', icon: Network, href: './explorer/' },
  { name: 'Mastery', copy: 'Practice scripture recall with focused exercises and review.', icon: Bookmark, href: './more/' },
  { name: 'Reading Plans', copy: 'Choose what you want to study, set your pace, and keep moving forward.', icon: Route, href: './more/' },
  { name: 'Notes & Highlights', copy: 'Capture what stands out without separating it from the scripture that inspired it.', icon: Highlighter, href: './reader/' },
  { name: 'Library', copy: 'Keep the passages, notes, highlights, and saved material you want to return to.', icon: Library, href: './more/' },
  { name: 'Study Spaces', copy: 'Create a private place for a family, class, or group to study together.', icon: Users, href: './groups/' },
  { name: 'Lessons', copy: 'Build reusable lessons, invite participation, and publish recurring teaching to Channels.', icon: NotebookPen, href: './lessons/' },
]

function App() {
  return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="container nav-shell"><Brand /><nav className="desktop-nav" aria-label="Primary navigation">{nav.map(([href, name]) => <a key={href} href={href}>{name}</a>)}</nav><div className="nav-actions"><a className="button primary nav-download" href="./download/">Download Cultivate</a><details className="mobile-menu"><summary>Menu</summary><nav aria-label="Mobile navigation">{nav.map(([href, name]) => <a key={href} href={href} onClick={event => event.currentTarget.closest('details')?.removeAttribute('open')}>{name}</a>)}<a href="./download/">Download</a></nav></details></div></div></header>
  <main id="main" tabIndex={-1}>
    <section className="hero container"><p className="tagline"><span />Read. Study. Teach. Together.</p><h1>Scripture study, built for <br /><em>more than reading.</em></h1><p className="hero-copy">Study deeply on your own. Explore the people, places, events, and connections behind the scriptures. Study together in private spaces. Build lessons, create ongoing channels, and bring everyone together live.</p><div className="actions"><Button href="./download/">Download Cultivate</Button><Button href="#experiences" secondary>Explore Cultivate</Button></div><p className="platform-note">iPhone &amp; iPad via TestFlight · Android beta</p><nav className="hero-doors" aria-label="The three Cultivate experiences"><a href="#study">Study</a><span aria-hidden="true">·</span><a href="#together">Together</a><span aria-hidden="true">·</span><a href="#teach">Teach</a></nav><HeroDevices /></section>
    <section className="experiences container" id="experiences"><SectionHeading eyebrow="Three ways to use Cultivate" title={<>Personal study. Shared study. Teaching.<br />All connected.</>}>Cultivate is designed for the whole scripture-study experience—from reading and discovery to studying with others and teaching what you learn.</SectionHeading>
      <div className="experience" id="study"><div className="experience-copy"><p className="section-chip">Study</p><h2>Make scripture study yours.</h2><p>Read one verse at a time when you want to slow down, or open the full chapter when you want the bigger picture. Then go beyond the text with Explorer and follow the people, places, events, stories, and relationships connected to what you’re reading.</p><p>Save notes, highlights, bookmarks, passages, and discoveries to return to later. Build consistency with reading plans and strengthen recall with Mastery.</p><a className="text-link" href="./study/">Explore personal study <ArrowRight size={15} /></a></div><ProductVisual className="study-product" caption="Conceptual Reader and saved-study layout"><ReaderView /><LibraryPreview /></ProductVisual></div>
      <div className="experience reverse" id="together"><div className="experience-copy"><p className="section-chip">Together</p><h2>Scripture study<br />is better together.</h2><p>Create a private Study Space for your family, friends, class, or group. Follow a plan together, see shared progress, exchange scripture-linked thoughts, and stay connected between the moments when everyone is in the same room.</p><p>Study Spaces give ongoing scripture study a home—whether your group meets every week or your family lives across different time zones.</p><a className="text-link terracotta" href="./together/">Explore Study Spaces <ArrowRight size={15} /></a></div><ProductVisual className="space-product" caption="Conceptual Study Space · No real member activity shown"><SpaceView /></ProductVisual></div>
      <div className="experience" id="teach"><div className="experience-copy"><p className="section-chip">Teach</p><h2>Turn your study<br />into a lesson.</h2><p>Build reusable lessons from scripture passages, questions, notes, saved material, and discoveries from your study. Share a lesson directly or publish it to a Lesson Channel your class or family can return to again and again.</p><p>Let participants work through a lesson at their own pace, or bring everyone together in a Live Class. Live Classes are currently available through invite-only Early Access.</p><a className="text-link" href="./teach/">Explore teaching <ArrowRight size={15} /></a></div><ProductVisual className="pillar-builder" caption="Conceptual Lesson Builder · Scripture, content, and questions"><BuilderView /></ProductVisual></div>
    </section>
    <Showcases />
    <section className="workflow" id="workflow"><div className="container"><SectionHeading eyebrow="Everything works together" title="One app. One study workflow.">What starts as personal scripture study can become something you save, share, and teach.</SectionHeading><div className="workflow-grid">{workflow.map(({ name, copy, detail, icon: Icon }, index) => <article className="workflow-card" key={name}><div className="workflow-card-head"><span>{String(index + 1).padStart(2, '0')}</span><Icon size={20} aria-hidden="true" /></div><h3>{name}</h3><p>{copy}</p><div className="workflow-detail">{detail}</div></article>)}</div><p className="workflow-note">Cultivate is designed so these experiences connect. Personal study can become saved material. Saved material can become a lesson. Lessons can become an ongoing channel. And the people you study with can participate wherever they are.</p></div></section>
    <section className="depth container"><SectionHeading eyebrow="A thoughtful set of tools" title="There’s more beneath the surface.">Go as deep as you want. The tools are there when you need them.</SectionHeading><div className="depth-grid">{features.map(({ name, copy, icon: Icon, href }) => <a className="depth-feature" href={href} key={name}><span className="feature-icon"><Icon size={18} aria-hidden="true" /></span><h3>{name}</h3><p>{copy}</p></a>)}</div></section>
    <section className="about container" id="about"><div><p className="eyebrow">Built to support your study</p><h2>Context to explore.<br /><em>Meaning to discover.</em></h2><p>Cultivate gives you scripture and structured context to explore while leaving interpretation, questions, and personal understanding with you.</p><a className="text-link" href="./labs/">Behind the connections: Cultivate Labs <ArrowRight size={15} /></a></div><div className="trust-points"><article><WifiOff size={21} /><div><h3>Useful offline.</h3><p>Scripture reading, Explorer data, personal study tools, and lesson building can remain useful without a connection. Sync, sharing, group activity, and Live require one.</p></div></article><article><BookOpen size={21} /><div><h3>No AI-generated scripture commentary.</h3><p>Explorer uses prepared, structured data and scripture evidence rather than generating interpretations of scripture at runtime.</p></div></article><article><LockKeyhole size={21} /><div><h3>Your study stays yours.</h3><p>Personal notes and teacher notes stay private unless you choose to share something.</p></div></article></div></section>
    <section className="download-cta" id="download"><div className="container"><p className="tagline"><span />Start studying with Cultivate</p><h2>Study deeper. Study together.<br /><em>Teach what you learn.</em></h2><p>Start with scripture and let Cultivate grow with the way you study.</p><div className="actions"><Button href="./download/">Download Cultivate</Button><Button href="#study" secondary>Explore Study</Button></div><p className="platform-note">iPhone &amp; iPad via TestFlight · Android beta</p><p className="beta-note">Features and availability may change during beta.</p></div></section>
  </main><footer><div className="container footer-grid"><div className="footer-brand"><Brand /><p>One place to study scripture, explore deeper, grow together, and teach what you learn.</p></div><nav aria-label="Study links"><h3>Study</h3><a href="./study/">Study overview</a><a href="./reader/">Scripture Reader</a><a href="./explorer/">Explorer</a><a href="./topical-guide/">Topical Guide</a><a href="./more/">Mastery &amp; plans</a></nav><nav aria-label="Together links"><h3>Together &amp; Teach</h3><a href="./together/">Together overview</a><a href="./teach/">Teach overview</a><a href="./groups/">Study Spaces</a><a href="./lessons/">Lessons</a><a href="./channels/">Lesson Channels</a><a href="./live/">Live · Early Access</a><a href="#workflow">The study workflow</a></nav><nav aria-label="About links"><h3>Cultivate</h3><a href="#about">Our approach</a><a href="./labs/">Cultivate Labs</a><a href="./download/">Download</a></nav></div><div className="container footer-bottom"><p>Cultivate is an independent application and is not affiliated with, nor officially supported or endorsed by, The Church of Jesus Christ of Latter-day Saints.</p><div><span>© {new Date().getFullYear()} Cultivate Study</span><a href="/new/privacy/">Privacy</a><a href="/new/account-deletion/">Account deletion</a></div></div></footer></>
}

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
