import { useRef } from 'react'
import { ArrowRight, BookOpen, MapPin, Network, Presentation, Users } from 'lucide-react'
import { Button, Device, ProductVisual, SpaceView } from './components'

export function Showcases() {
  const access = useRef<HTMLDialogElement>(null)
  return <div className="showcases">
    <section className="showcase container" id="explorer-showcase">
      <div className="showcase-copy"><p className="eyebrow">Study / Explorer</p><h2>See the scriptures<br /><em>differently.</em></h2><p>Explore the people, places, events, stories, groups, and relationships behind what you’re reading. Follow one connection into another part of the story, then return directly to the scripture evidence behind it.</p><p>Explorer turns scripture context into something you can browse and discover—not generated commentary telling you what the text means.</p><Button href="./explorer/">Explore Explorer</Button></div>
      <ProductVisual className="explorer-showcase" caption="Conceptual Explorer view · Scripture references are real"><div className="explorer-demo"><div className="ui-toolbar"><Network size={16} /><span>SCRIPTURE EXPLORER</span></div><div className="explorer-body"><p className="ui-eyebrow">From a passage to its context</p><h3>Paul in Philippi</h3><p className="ui-description">People, places, and a story connected by scripture.</p><div className="context-map"><div className="context-node"><Users size={19} /><span>Person</span><strong>Paul</strong><small>Acts 16:12–13</small></div><div className="context-node place"><MapPin size={19} /><span>Place</span><strong>Philippi</strong><small>Acts 16:12</small></div><div className="context-node event"><BookOpen size={19} /><span>Event</span><strong>Lydia hears Paul</strong><small>Acts 16:13–15</small></div></div><div className="evidence-strip"><span className="ui-eyebrow">Return to the evidence</span><p>“a certain woman named Lydia … heard us”</p><span className="reference-chip">Acts 16:14 · KJV</span></div><div className="ui-chips"><span>People</span><span>Places</span><span>Events &amp; stories</span><span>Groups</span><span>Connections</span></div></div></div></ProductVisual>
    </section>
    <section className="space-showcase-band" id="spaces-showcase"><div className="showcase container reverse-showcase"><div className="showcase-copy"><p className="eyebrow">Together / Study Spaces</p><h2>Give your group a place<br /><em>to keep studying.</em></h2><p>Scripture study doesn’t have to end when everyone goes home. A Study Space gives your group one private place for shared reading, progress, thoughts, lessons, and continued participation.</p><p>Use it with your family, friends, a class, or a group spread across different homes and time zones. Everyone can participate on their own schedule and return when the group comes together again.</p><Button href="./groups/">Explore Study Spaces</Button></div><ProductVisual className="persistent-space" caption="Conceptual family Study Space · Illustrative progress, not real member activity"><div className="scenario-label"><Users size={16} /><span>Family study · Across different time zones</span></div><SpaceView /><div className="space-continuity"><span>Read at your pace</span><ArrowRight size={14} /><span>Share a thought</span><ArrowRight size={14} /><span>Return together</span></div></ProductVisual></div></section>
    <section className="channel-showcase container" id="channels-showcase"><div className="section-heading"><p className="eyebrow">Teach / Lesson Channels</p><h2>Give your teaching <em>a home.</em></h2><p>A lesson can be shared once. A Lesson Channel gives recurring teaching a place to continue. Publish new lessons to the same channel and let your class or family return week after week.</p></div><div className="channel-layout"><ProductVisual caption="Conceptual Lesson Channel · Example lesson sequence"><div className="channel-demo"><div className="ui-toolbar"><Presentation size={16} /><span>LESSON CHANNEL</span><span className="privacy-chip">Your class</span></div><div className="channel-body"><p className="ui-eyebrow">A home for recurring lessons</p><h3>Seminary</h3><p className="ui-description">The same class. A new lesson. A continuing conversation.</p>{[['Previous lesson','Come and see','John 1:35–51'],['This week','Abide in me','John 15:1–11'],['Next lesson','Love one another','John 15:12–17']].map(([label,title,reference])=><div className="channel-lesson" key={label}><BookOpen size={18} /><div><span>{label}</span><h4>{title}</h4><p>{reference}</p></div><span className="reference-chip">Lesson</span></div>)}<div className="channel-modes"><span>Participate at your own pace</span><span>Meet live · Early Access</span></div></div></div></ProductVisual><div className="channel-scenarios"><article><p className="eyebrow">A continuing class</p><h3>Seminary</h3><p>Create a persistent home for a class with new lessons throughout the course. Students know where to return each time.</p></article><article><p className="eyebrow">Week after week</p><h3>Sunday School</h3><p>Share lessons before or after Sunday and keep participation connected from one week to the next.</p></article><article><p className="eyebrow">Across the miles</p><h3>Family Home Evening</h3><p>Bring an extended family together for recurring lessons even when everyone lives in different places.</p></article></div></div><p className="channel-flow">Build a lesson <span>→</span> Publish to a channel <span>→</span> Participate together <span>→</span> Return for the next lesson</p></section>
    <section className="live-showcase" id="live-showcase"><div className="container"><div className="live-heading"><div><p className="early-badge">Invite-only Early Access</p><p className="eyebrow">Teach / Live Classes</p><h2>Teach live<br /><em>from anywhere.</em></h2><p>Lead the lesson from your device while participants follow along on theirs. Move through scripture, questions, and lesson content together while everyone stays in the same place in the lesson.</p><p>Use Live for a classroom, a study group, or a family gathering across multiple homes.</p></div><div className="live-access"><button className="button" onClick={()=>access.current?.showModal()}>How to request Early Access <ArrowRight size={15} /></button><p>Live Classes are currently available by invitation and require an internet connection.</p><a href="#channels-showcase">Keep teaching between sessions <ArrowRight size={14} /></a></div></div><ProductVisual className="live-composition" caption="Conceptual host and participant views · Illustrative question, no real responses"><Device kind="tablet"><div className="live-host"><div className="ui-toolbar"><Presentation size={16} /><span>HOST / ABIDE IN ME</span></div><div className="live-host-body"><p className="ui-eyebrow">Leading the lesson</p><h3>Read. Reflect. Discuss.</h3><p className="live-scripture">“I am the vine, ye are the branches…”</p><span className="reference-chip">John 15:5</span><div className="live-question"><span>Shared question</span><h4>What does it mean to abide?</h4><p>The same passage and prompt, on everyone’s device.</p></div><p className="private-live-note">Your teacher notes stay private.</p></div></div></Device><Device kind="phone"><div className="live-participant"><div className="ui-toolbar"><BookOpen size={15} /><span>PARTICIPANT</span></div><p className="ui-eyebrow">Following the host</p><h4>Abide in me</h4><span className="reference-chip">John 15:5</span><p>“I am the vine, ye are the branches…”</p><div className="live-question"><span>Shared question</span><h4>What does it mean to abide?</h4><div className="response-preview">Your response…</div><small>Illustrative response field</small></div></div></Device></ProductVisual></div></section>
    <dialog ref={access} className="access-dialog" aria-labelledby="access-title"><form method="dialog"><p className="early-badge">Invite only</p><h2 id="access-title">Live Classes Early Access</h2><p>Early Access is requested inside Cultivate. Open the app, start a Live Session, and complete the Early Access request form when prompted.</p><p>If you do not have Cultivate yet, download the app first and request access from Live.</p><div className="actions"><Button href="./download/">Download Cultivate</Button><button className="button secondary" autoFocus>Close</button></div></form></dialog>
  </div>
}
